# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-09 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('id', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteid',
            name='site',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
            preserve_default=False,
        ),
    ]
