# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-09 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0002_siteid_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteid',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_id', to='sites.Site'),
        ),
    ]
