# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20170712_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
