# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_profile_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='desc',
            new_name='description',
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
