# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-04 06:49
from __future__ import unicode_literals

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BMC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'd', b'Draft'), (b'p', b'Published')], default=b'p', max_length=1)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Model Canvas',
                'verbose_name_plural': 'Business Model Canvas',
            },
        ),
        migrations.CreateModel(
            name='BMCEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('bmc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.BMC')),
            ],
            options={
                'verbose_name': 'BMC Entry',
                'verbose_name_plural': 'BMC Entries',
            },
        ),
        migrations.CreateModel(
            name='BMCField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
            options={
                'verbose_name_plural': 'BMC Fields',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Company Title')),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name=b'image')),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('section', models.CharField(default=b'', max_length=200, verbose_name='Business Field')),
                ('description', models.TextField(blank=True, verbose_name='Company Description')),
                ('wiki', models.URLField(blank=True, verbose_name='Wiki URL')),
                ('url', models.CharField(blank=True, max_length=200, verbose_name='Website')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='SWOT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'd', b'Draft'), (b'p', b'Published')], default=b'p', max_length=1)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.Company')),
            ],
            options={
                'verbose_name_plural': 'SWOT',
            },
        ),
        migrations.CreateModel(
            name='SWOTEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'SWOT Entry',
                'verbose_name_plural': 'SWOT Entries',
            },
        ),
        migrations.CreateModel(
            name='SWOTField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
            options={
                'verbose_name_plural': 'SWOT Fields',
            },
        ),
        migrations.CreateModel(
            name='VPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'd', b'Draft'), (b'p', b'Published')], default=b'p', max_length=1)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.Company')),
            ],
            options={
                'verbose_name': 'Value Proposition Canvas',
                'verbose_name_plural': 'Value Proposition Canvas',
            },
        ),
        migrations.CreateModel(
            name='VPCEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'VPC Entry',
                'verbose_name_plural': 'VPC Entries',
            },
        ),
        migrations.CreateModel(
            name='VPCField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
            options={
                'verbose_name_plural': 'VPC Fields',
            },
        ),
        migrations.AddField(
            model_name='vpcentry',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.VPCField'),
        ),
        migrations.AddField(
            model_name='vpcentry',
            name='vpc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.VPC'),
        ),
        migrations.AddField(
            model_name='swotentry',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.SWOTField'),
        ),
        migrations.AddField(
            model_name='swotentry',
            name='swot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.SWOT'),
        ),
        migrations.AddField(
            model_name='bmcentry',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.BMCField'),
        ),
        migrations.AddField(
            model_name='bmc',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.Company'),
        ),
    ]
