# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20170707_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category1', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='company',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
