# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_auto_20170707_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Tool Entry',
                'verbose_name_plural': 'Tool Entries',
            },
        ),
        migrations.CreateModel(
            name='ToolField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Tool Field',
                'verbose_name_plural': 'Tool Fields',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='section',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='wiki',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='toolfield',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Category'),
        ),
        migrations.AddField(
            model_name='toolentry',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.ToolField'),
        ),
        migrations.AddField(
            model_name='toolentry',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Tool'),
        ),
    ]
