# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_auto_20170707_2009'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ToolCategory',
        ),
        migrations.AlterModelOptions(
            name='toolcategory',
            options={'verbose_name': 'Tool Category', 'verbose_name_plural': 'Tool Categories'},
        ),
    ]
