# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_remove_toolentry_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.Company'),
        ),
    ]
