# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 22:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_auto_20170708_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swot',
            name='author',
        ),
        migrations.RemoveField(
            model_name='swot',
            name='company',
        ),
        migrations.RemoveField(
            model_name='swotentry',
            name='category',
        ),
        migrations.RemoveField(
            model_name='swotentry',
            name='swot',
        ),
        migrations.DeleteModel(
            name='SWOT',
        ),
        migrations.DeleteModel(
            name='SWOTEntry',
        ),
        migrations.DeleteModel(
            name='SWOTField',
        ),
    ]
