# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-08 07:38
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_auto_20170708_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolfield',
            name='hint',
            field=models.TextField(default='dadadasd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toolfield',
            name='icon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name=b'image'),
        ),
    ]
