# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-08 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_auto_20170708_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
