# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-11 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_auto_20170708_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolentry',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='business.ToolCategory'),
            preserve_default=False,
        ),
    ]
