# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-11 18:08
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_toolentry_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolentry',
            name='field',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'category', chained_model_field=b'category', on_delete=django.db.models.deletion.CASCADE, to='business.ToolField'),
        ),
        migrations.AlterField(
            model_name='toolentry',
            name='tool',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'category', chained_model_field=b'category', on_delete=django.db.models.deletion.CASCADE, to='business.Tool'),
        ),
    ]
