# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-11 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_auto_20170711_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolfield',
            name='hint',
            field=models.TextField(blank=True),
        ),
    ]
