# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-20 00:14
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_auto_20170718_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='toolfield',
            name='hint',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='toolfield',
            name='icon',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
