# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-20 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0021_auto_20170720_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolcategory',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='toolfield',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
