# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-31 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0022_auto_20170720_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='section',
            field=models.CharField(max_length=200),
        ),
    ]
