# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-04 06:49
from __future__ import unicode_literals

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('text', models.TextField()),
                ('featured_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name=b'image')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'd', b'Draft'), (b'p', b'Published')], default=b'p', max_length=1)),
                ('title', models.CharField(max_length=200, verbose_name='Post Title')),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('featured_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name=b'image')),
                ('text', models.TextField(verbose_name='Post Content')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category')),
            ],
        ),
    ]
