# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-24 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20170806_1537'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
